kind: Deployment
apiVersion: apps/v1beta2
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
  namespace: default
spec:
  replicas: {{ .Values.replicaCount }}
{{- if .Values.updateStrategy }}
  strategy:
{{ toYaml .Values.updateStrategy | indent 4 }}
{{- end }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        resources:
{{ toYaml .Values.resources | indent 12 }}
        env:
        - name: STREAM_REGISTRY_BOOTSTRAP_SERVERS
          value: "{{ .Chart.Name }}-kafka:9092"
        - name: STREAM_REGISTRY_SCHEMA_REGISTRY_URL
          value: "http://{{ .Chart.Name }}-schema-registry:8081"