{{- if .Values.ingress.enabled -}}
{{- $path := .Values.ingress.path -}}
{{- $serviceName := .Chart.Name -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
  namespace: default
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: {{ $path }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: 80
    {{- end -}}
{{- end -}}
