apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: {{ .Chart.Name }}