---
spring:
  jpa:
    properties:
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        cache:
          region:
            factory_class: "org.hibernate.cache.ehcache.EhCacheRegionFactory"
          use_second_level_cache: true
          use_query_cache: true
        generate_statistics: true
    hibernate:
      temp:
        use_jdbc_metadata_defaults: false
      jdbc:
        lob:
          non_contextual_creation: true
      ddl-auto: validate
      database-platform: "org.hibernate.dialect.PostgreSQLDialect"
      show-sql: true
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
